# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:lts-alpine

pipelines:
  default:
    - step:
            script:
              - npm install
              - npm install express --save
              - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
              - docker build -t kstanyslaw/snnews:bitbucket .
              - docker push kstanyslaw/snnews:bitbucket
            services:
              - docker